### PR TITLE
Device dashboard v2

### PR DESCRIPTION
**Pull request by pechouc**
This PR proposes to update the device connectivity dashboard of the platform by introducing: 

- a few design corrections (size of the main table, section titles...);
- a new section with an overview of the connectivity status at the site level;
- a bit of documentation.

Thanks a lot for the review 😊

### CODE REVIEW

**Comment by frgfm** [comment]
ping @Akilditu @pechouc, we should move forward with this PR :sweat_smile: 
Can someone review it please? :pray:

**Comment by frgfm** [comment]
Could we add a screenshot and move forward with the PR please? :) 
@pyronear/front-end

**Comment by frgfm** [comment]
Alright, time to do something with this PR @pyronear/back-end :sweat_smile: 
Should we close it or can we merge it? We need some reviews here @Akilditu :pray:

**Comment by MateoLostanlen** [comment]
This is quite old let's close it

**Pull request closed without merging**
