### PR TITLE
Fetching GeoJSON file from Pyro-Risk release

### PR DESCRIPTION
**Pull request by pechouc**
Hello everyone!

Following #35, here is a very light PR to switch from reading the local GeoJSON file in the `data` folder to fetching the file online, from a [release](https://github.com/pyronear/pyro-risks/releases/tag/v0.1.0-data) in the Pyro-Risk repository. 

The first commit thus changes:
- the `alerts.py` file to (i) move the file reading procedure outside of the `build_departments_geojson` function, (ii) modify this process from a local reading to the online one and (iii) adapt imports and comments as needed;
- the `risks.py` file in which the file reading procedure was already outside of the function;
- the `config.py` file, so as to store the URL towards the release in a clean way. 

The second commit simply consists in eliminating the unnecessary local file. 

My only interrogation is the following. Because the file is the same for both alerts and risks views, we could theoretically fetch the file only once for both, which would be more efficient. But at the same time, in `risks.py`, we are also fetching the estimated risk scores from the data science team and use them to modify the `departments` variable. So, it seems that it would require some work to merge both requests to the online file and it feels as a bit of an overkill to me. 

What is your opinion on this? Should we absolutely read the file only once for both maps?

### CODE REVIEW

**Review by chloeskt — CHANGES_REQUESTED** [review]
Hi @pechouc ! Thank you for this PR, seems great !! 

I've had a look at this issue given by [Codacy](https://app.codacy.com/gh/pyronear/pyro-platform/pullRequest?prid=6956940). This is that there are security issues with `urllib`, especially due to the permitted schemes ([SO thread](https://stackoverflow.com/questions/48779202/audit-url-open-for-permitted-schemes-allowing-use-of-file-or-custom-schemes)). I guess that the security risk is not that important in our case, but we should try to have as many best practices as possible. Maybe we should use another library such as `requests` which do not face the same issue ? or make sure that the transfer protocol is http or https if you want to use ` urllib` ?

**Comment by pechouc** [comment]
Thanks for the heads-up, I had missed the Codacy check! I have moved to `requests` in a new commit, which presents the additional advantage of harmonising these few lines with the process already used for getting the risk score.

**Review by chloeskt — APPROVED** [review]
That is great !

**Comment by frgfm** [comment]
Just updated @chloeskt access to the repo, you now have write access :ok_hand: 
So @pechouc, you can move ahead with the merge if everything looks alright to you :)

**Comment by chloeskt** [comment]
Thanks @frgfm ☺️

**Comment by pechouc** [comment]
Wonderful, thanks a lot!

**Pull request merged**
