### PR TITLE
adding historic fires

### PR DESCRIPTION
**Pull request by abdi-adel**
### Aim of the Pull Request :

Adding the historic fires on both 'alerts' and 'risks' map.

**More detailed info:**

**_Adding made :_**

Adding a new dataset "historic_fires.csv" in 'data' folder
Adding a new callback in 'Callbacks related to the "Niveau de Risque" page' in main.py
Adding a new callback in 'Callbacks related to the "Alertes et Infrastructures" dashboard' in main.py

Adding two functions in utils.py : get_old_fire_positions* and build_historic_markers functions
*in this first function, we also customised the markers of the historic fires to improve the visualization on the map

Adding some imports in utils.py

Adding a new button* in the homepage.py:
*the new button allows to visualize or not the historic fires on the map

**_Changing made:_**
Editing the build_risks_map() function by adding the build_historic_markers in risks.py
Editing the build_alerts_map() function by adding the build_historic_markers in alerts.py

historic_fires_alert_on
historic_fires_alert_on_date
historic_fires_alert_off
historic_fires_alert_on_popup_schematique
historic_fires_alert_on_popup

Note 1 : No density filter

Thanks for reviewing

### CODE REVIEW

**Comment by pechouc** [comment]
Oops, I think I messed up while trying to make Flake8 modifications locally. I wanted to push my modifications on the remote `historic_fires` branch but the wrong local branch was pushed... I am looking for the simplest fix we could use.

**Review by nrslt — APPROVED** [review]
thanks for the PR guys, honestly not much to add, seems to work smoothly!

btw thanks for adopting the dead tree icon, I am well aware that it will be replaced at some point but it's nice to see it here :)

**Comment by pechouc** [comment]
The new PR ready for review is here: https://github.com/pyronear/pyro-platform/pull/25!

**Comment by Akilditu** [comment]
> The new PR ready for review is here: #25!


Shall we close this one ?

**Comment by pechouc** [comment]
> Shall we close this one ?

Yes, I just wanted to wait a bit before closing it, so that comments having disappeared from one PR to the other would not be surprising but we do not need it anymore.

**Pull request closed without merging**
