### PR TITLE
adding past fires

### PR DESCRIPTION
**Pull request by abdi-adel**
### Aim of the Pull Request :

Adding the historic fires on both 'alerts' and 'risks' map.

**More detailed info:**

**_Adding made :_**

Adding a new dataset "historic_fires.csv" in 'data' folder
Adding a new callback in 'Callbacks related to the "Niveau de Risque" page' in main.py
Adding a new callback in 'Callbacks related to the "Alertes et Infrastructures" dashboard' in main.py

Adding two functions in utils.py : get_old_fire_positions* and build_historic_markers functions
*in this first function, we also customised the markers of the historic fires to improve the visualization on the map

Adding some imports in utils.py

Adding a new button* in the homepage.py:
*the new button allows to visualize or not the historic fires on the map

**_Changing made:_**
Editing the build_risks_map() function by adding the build_historic_markers in risks.py
Editing the build_alerts_map() function by adding the build_historic_markers in alerts.py

historic_fires_alert_on
historic_fires_alert_on_date
historic_fires_alert_off
historic_fires_alert_on_popup_schematique
historic_fires_alert_on_popup

Note 1 : No density filter

Thanks for reviewing

### CODE REVIEW

**Comment by Akilditu** [comment]
Great PR, thanks a lot @abdi-adel and @pechouc !

Overall it seems just fine, the only important features that I would discuss here is the past fires marker design. Even if singular, those 'dead trees' icons may not be appropriate for a professional use. 

Waiting for other reviewers inputs on this ?

**Comment by pechouc** [comment]
> Even if singular, those 'dead trees' icons may not be appropriate for a professional use.

For sure and actually, we have not spent much time (or any time?) looking for the most appropriate icon.

But thinking about it, I feel like there are not many possibilities, considering that the alert sign already contains a fire representation. If we keep the alert marker this way, I guess we could come back to a traditional geographical pointer...

Or maybe, we could move the alert sign to something [in this vein](https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Exclam_icon.svg/1200px-Exclam_icon.svg.png), which would allow to use a fire sign for historic markers?

**Review by vincent-gargasson-aqsone — APPROVED** [review]
great input ! Thanks @abdi-adel for this first PR (and @pechouc )
Overall syntax and doc string format looks good to me. And it's good idea to bring back those markers even when we play with the risk color opacity.
I do agree with @Akilditu's remark regarding the dead tree. But so far we have used many of the icon possiblities.

**Comment by pechouc** [comment]
## Edits done

- Adding `.png` files of marker icons to the `assets` folder
- Changing marker icons based on these new files
- Adding a static legend to both "Alertes" and "Niveaux de Risque" maps

## How it renders locally

Capture d’écran 2020-12-09 à 14 45 14

---

Capture d’écran 2020-12-09 à 14 45 37

---

Capture d’écran 2020-12-09 à 14 46 06

## Additional screenshot 

Because we cannot see well the legend in production mode, here is an indication of how the legend looks:

Capture d’écran 2020-12-09 à 14 46 36

**Review by Akilditu — CHANGES_REQUESTED** [review]
Thanks a lot for the PR guys ! 

Could you delete unused imports as described in codacy report before being able to merge

**Review by nrslt — APPROVED** [review]
thanks adel and PE for this PR, it looks fine to me !
only remarks:
we will have to see how to access the icon png files in a 'cleaner' way with Path() for example
we can discuss later the best way to display sites/alerts icons

**Review by Akilditu — APPROVED** [review]

**Pull request merged**
