### PR TITLE
compose: updating prod compose file

### PR DESCRIPTION
**Pull request by Akilditu**
This PRs aims at adding a docker-compose-prod.yml deployed on VMs that does the following:

1. Stop building `frontend` service from local folder 
2. Using the image instead from `pyronear/pyro-platform:latest`

Any feedback is welcome !

### CODE REVIEW

**Review by MateoLostanlen — APPROVED** [review]
thanks for the update ! Please check the docker build issue before merging !

**Comment by MateoLostanlen** [comment]
@Akilditu if you are changing the file name I guess you need to update [this](https://github.com/pyronear/pyro-platform/blob/2bf81292dfe4d5563e584e619c6ae62e6a48af11/.github/workflows/push.yml#L40) accordingly

**Comment by Akilditu** [comment]
> @Akilditu if you are changing the file name I guess you need to update [this](https://github.com/pyronear/pyro-platform/blob/2bf81292dfe4d5563e584e619c6ae62e6a48af11/.github/workflows/push.yml#L40) accordingly

True actually, moreover this needs to be renamed on VMs as well. I just did it to the ubuntu one.

**Review by MateoLostanlen — APPROVED** [review]
thanks for the update !

**Comment by Akilditu** [comment]
> > @Akilditu if you are changing the file name I guess you need to update [this](https://github.com/pyronear/pyro-platform/blob/2bf81292dfe4d5563e584e619c6ae62e6a48af11/.github/workflows/push.yml#L40) accordingly
> 
> True actually, moreover this needs to be renamed on VMs as well. I just did it to the ubuntu one.

Nope actually the simple way for dev VM is to have a proper compose.yml with the subdomain variation for traefik no need to have it tracked within main repo. 

You can check how it is there.

**Pull request merged**
