### PR TITLE
update dependance of the projet ( dash also ) , find the bug and find a work around 

### PR DESCRIPTION
**Pull request by TimotheDavid**
Hey I have fix the dep ( why it's doesn't work :) now it's dash > 2 
I ahve find a work around for the bug about the screen ( resize the screen ( yess it's work !) 

thnaks for accpet my pr

### CODE REVIEW

**Review by Akilditu — COMMENTED** [review]
Hi @TimotheDavid, sorry for the late concern, few questions here :

- The motivation of this PR is to provide a fix for the force resize of the browser tab that was needed to display the map right ? 
- The typo changes that you did are requested by a recent dash version update ?

Thanks for the PR !

**Comment by frgfm** [comment]
> Hi @TimotheDavid, sorry for the late concern, few questions here :
> 
> * The motivation of this PR is to provide a fix for the force resize of the browser tab that was needed to display the map as explained [here](https://github.com/pyronear/pyro-platform/issues/71) right?
> * The typo changes that you did are requested by a recent dash version update ?
> 
> Thanks for the PR !

If specifying a max version of dash does the trick, perhaps that would be easier :+1:

**Comment by frgfm** [comment]
> If specifying a max version of dash does the trick, perhaps that would be easier +1

What do you think @TimotheDavid? :)

**Comment by Akilditu** [comment]
> > If specifying a max version of dash does the trick, perhaps that would be easier +1
> 
> What do you think @TimotheDavid? :)

Hi definitely think that it's the best solution !

**Comment by frgfm** [comment]
Hello everyone :wave: 

Reading the conversation again, I think we have to use the version specifiers to solve this problem. I opened a dedicated issue for this #76, so I'll close this PR.

Feel free to reopen if you think it's relevant :)

**Pull request closed without merging**
